version: '3.1'

services:

  db:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodata:/data/db

  web:
    image: uofusomd/php_mongo_gd
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DB_URL: mongodb://db/ojr
      enc_key: jsuahyy639Ah32kj^gs
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html

volumes:
  mongodata:

